language: node_js
node_js:
- 7.7.3
script:
- yarn test
- yarn build
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
before_script:
- yarn install
deploy:
  provider: heroku
  api-key:
    secure: H0HijxgXyysRXgbmamIXJwq7w8wmWx3ECYHZDDRQYyQClAxDFYKvNYwLjlKgpAtzYD8vJBUsDAi3kECu95dPBLn8JfAhTuWJC0MLUCL256eHoKr3RifYbGSU2hAPqqwPr8gblO3Rl2vqJSdqpA99/3H4lGxVLvxyz7WgaGti3O/6B1BfvCuuAVXQLdjU8PThtd2YkZRF8XGrwGDVEjgY4oIrOIPWVOpbbyVyxo+0LzyIMsusoQdMuECu8iezxp42Wt39vdLAuddI8wh5YqEDRSrycmslCbGouFvsBb7p4UqCW5w4GDaV1DgH6vcndi0aOOGwhzkfLTiEvy8gKeL5p9/59hkscwmDm280Tw3/A3lphWaa3cO1AIlBvHiTgvoRPw2Y9h2udV/gYygbe6c2cH1b1kgovjL2KZbhUFeRgw+Awblu+pMXcZQN+EJME9FUe21C5J3RlZW5APBb1k47eSrDesXUT1mRXJuwLj2zUriAnOVm4wNonUgwUpvmMf4ly/SHO/GNHiosDhOLnQm0jlNT7R7HGnK1D3JuPssYTmJNBJ2IvgytmI7frjgKvN83POP2eQLCEgaOijkNaM4TBHw1hp7Bh5G9QSAw9CCg46SPeIze8K/jqyXz+4R6y/e7dprNvtOmF/wsF/fAz7MjeVxZofUlgf2qLWUuCnqte20=
  app:
    master: icomrade-front
    develop: icomrade-front-dev
  on:
    repo: anhnguyen300795/iComrade-front
  api_key:
    secure: KsYkhKt9mLruILCoAvlpeMDgBocYFb6UDtDkwYI4dq+YUqlpW5SAYx/3CQymf9eNwq1tra/+xgs7Bms0Amy4SUV9oiJ0Kj4wjpNfXVzAc5Xp+thKznyeRpNCkLO90himgn2z8kwwjmHOxn8TaFEvQad2Gt1R22W6TYPyf7rmSGkwkkniI+mrvQkwshS6bdiMMKWO1s6neOg7usOYrNHR25dcxIBXBVehlCoXiZ1rWIpmh3tkwil2ceebQPV80+z0JLqek/CNFomLPl+EKla6267SOxTePW5nu82EYPOwOFzjXDK+JDu9UPB3X2rxJBFPLolfx0/qFV2YsO71m70NrWst0M1Q2BeUXAWJDNVlzK4lC9RiDrxix2ne5edTAZPmxRZF1a0/o5vPXjr02Y6ZYu7e5eUCMUd6NgmZl3QPY6N5umoR8EPrjqehD/vUx9p9AhziO1h52hOYUhtl3VHZ6eDQPY87Z8PbPmQ1UFJrboUUk9kOJOaZxgMmKvKDAUhibm1qEsXIeC0jI9EiXXQEKvAC9FLOFBE+P67+c3h57F+2vKTgw49yeXHU1pyQsDWmaMnuzwS+CxMLCHn1d7zqT1kzcfprtWMgj8i/63HDG94JOACE5wUS+nT6dAJLpdu7bD2clYLfK2XziavrAaPhPmqF2d2XgdbJpWLsQCOyA5s=
